name: Repo events
on: [push, pull_request,issues]

jobs:
    event-demo:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo $GITHUB_REF
            - uses: actions/checkout@v3

