name: first flow
on: [push]
jobs:
    run-shell-commands:
        runs-on: ubuntu-latest
        steps:
            - name: echo string
              run: echo "hello world"
            - name: node version
              run: |
                node -v
                npm -v
        